### ISSUE TITLE
deprecate in favour of more up to date tianon/qemu

### ISSUE THREAD

**Issue by graingert** [Ulexus/docker-qemu#1]
https://github.com/tianon/dockerfiles/tree/master/qemu

**Comment by Ulexus** [comment]
Nice; thanks!

**Comment by graingert** [comment]
@Ulexus fyi @tianon is a member of @docker

**Comment by Ulexus** [comment]
Yes, I'm aware.  I'm much happier to have qemu in the main library.

**Comment by Ulexus** [comment]
Fixed by 38f0a68a00b7bc53aa83c9709f89a0290d51f6e4
